bind_var_errors.m:033: In clause for `bind_var_in_negation':
bind_var_errors.m:033:   scope error: attempt to bind a non-local variable
bind_var_errors.m:033:   inside a negation.
bind_var_errors.m:033:   Variable `X' has instantiatedness `free',
bind_var_errors.m:033:   expected instantiatedness was `unique(42)'.
bind_var_errors.m:039: In clause for `bind_var_in_ite_cond(in)':
bind_var_errors.m:039:   scope error: attempt to bind a non-local variable
bind_var_errors.m:039:   inside the condition of an if-then-else.
bind_var_errors.m:039:   Variable `Y' has instantiatedness `free',
bind_var_errors.m:039:   expected instantiatedness was `unique(42)'.
bind_var_errors.m:048: In clause for `bind_var_in_lambda':
bind_var_errors.m:048:   in argument 1 (i.e. the predicate term) of
bind_var_errors.m:048:   higher-order predicate call:
bind_var_errors.m:048:   mode error: variable `Y' has instantiatedness `free',
bind_var_errors.m:048:   expected instantiatedness for non-local variables of
bind_var_errors.m:048:   lambda goals is `ground'.
bind_var_errors.m:053: In clause for `share_var_in_lambda(di)':
bind_var_errors.m:053:   in argument 1 of call to predicate
bind_var_errors.m:053:   `bind_var_errors.destroy'/1:
bind_var_errors.m:053:   mode error: variable `X' has instantiatedness
bind_var_errors.m:053:   `ground',
bind_var_errors.m:053:   expected instantiatedness was `unique'.
bind_var_errors.m:060: In clause for `clobber_var_in_lambda(di)':
bind_var_errors.m:060:   in argument 1 of call to predicate
bind_var_errors.m:060:   `bind_var_errors.destroy'/1:
bind_var_errors.m:060:   unique-mode error: the called procedure would clobber
bind_var_errors.m:060:   its argument, but variable `X' is still live.
For more information, recompile with `-E'.
